name: Python Tests

on:
  push:
    branches:
      - aula08-testes

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout do projeto
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar pytest
        run: pip install pytest

      - name: Rodar testes
        run: pytest -v